theme: jekyll-theme-cayman
title: Welcome to the Latinx Code!
description: Here you will find links to sample code used in the Latinx Code curriculum, as well as to our social media channels, where can be easily accessed.
